name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Configurar Android SDK oficial
      uses: android-actions/setup-android@v3

    - name: Instalar dependencias base
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk python3-pip build-essential \
          libssl-dev libffi-dev libsqlite3-dev zlib1g-dev libjpeg-dev libfreetype6-dev \
          libpng-dev git libtool m4 automake autoconf

    - name: Instalar Buildozer y dependencias Python
      run: pip install --user buildozer cython

    - name: Decodificar keystore desde secreto
      run: echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > key.keystore

    - name: Compilar APK con Buildozer
      run: buildozer android release

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: SmashApp-APK
        path: bin/*.apk
