name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Instalar dependencias + SDK Android con estructura válida
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-11-jdk python3-pip build-essential \
          libssl-dev libffi-dev libsqlite3-dev zlib1g-dev libjpeg-dev libfreetype6-dev \
          libpng-dev git libtool m4 automake autoconf

        # Descargar y configurar command-line tools
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/temp
        mv $ANDROID_SDK_ROOT/cmdline-tools/temp/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools

        # Instalar plataforma y build-tools 36 + aceptar licencias
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" "platforms;android-33" "build-tools;36.0.0"

        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

    - name: Instalar Buildozer y dependencias Python
      run: pip install --user buildozer cython

    - name: Decodificar keystore desde secreto
      run: echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > key.keystore

    - name: Compilar APK con Buildozer
      run: buildozer android release

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: SmashApp-APK
        path: bin/*.apk
