name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: $HOME/Android/Sdk

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      - name: Pre-aceptar licencias del SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > \
            $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > \
            $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license

      - name: Aceptar licencias pendientes
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Instalar SDK Packages
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;36.0.0"

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk python3-dev python3-pip build-essential \
            libssl-dev libffi-dev libsqlite3-dev zlib1g-dev \
            libjpeg-dev libfreetype6-dev libpng-dev git \
            libtool libltdl-dev libtool-bin \
            autoconf automake pkg-config m4 autoconf-archive

      - name: Install Buildozer, Cython & python-for-android
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user \
            cython==0.29.34 \
            python-for-android==2023.5.21 \
            buildozer

      - name: Decode keystore from secret
        run: |
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > key.keystore

      - name: Build APK (release)
        run: |
          ~/.local/bin/buildozer android release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmashApp-APK
          path: bin/*.apk
